<?php

declare(strict_types=1);

return [
    'roles' => [
        'administrator' => [
            'label' => 'Administrator',
            'permissions' => ['*'],
        ],
        'geschaeftsfuehrung' => [
            'label' => 'Geschaeftsfuehrung',
            'permissions' => [
                'dashboard.view',
                'attendance.view',
                'users.manage',
                'roles.manage',
                'projects.manage',
                'files.manage',
                'assets.manage',
                'timesheets.view',
                'timesheets.manage',
                'timesheets.archive',
                'timesheets.export',
                'reports.export',
                'reports.accounting.export',
                'accounting.finalize',
                'time_accounts.view',
                'time_accounts.manage',
                'vacation_requests.view',
                'vacation_requests.manage',
                'personnel.view',
                'personnel.manage',
                'settings.manage',
                'settings.database.manage',
                'terminals.manage',
                'push.manage',
                'push.receive',
            ],
        ],
        'bauleiter' => [
            'label' => 'Bauleiter',
            'permissions' => [
                'dashboard.view',
                'attendance.view',
                'projects.manage',
                'files.upload',
                'files.view',
                'assets.assign',
                'timesheets.view',
                'timesheets.manage',
                'timesheets.export',
                'reports.export',
                'personnel.view',
                'push.receive',
            ],
        ],
        'kolonnenfuehrer' => [
            'label' => 'Kolonnenfuehrer',
            'permissions' => [
                'dashboard.view',
                'attendance.view',
                'projects.view',
                'files.upload',
                'files.view',
                'assets.assign',
                'timesheets.view',
                'timesheets.manage',
                'push.receive',
            ],
        ],
        'mitarbeiter' => [
            'label' => 'Mitarbeiter',
            'permissions' => [
                'projects.view',
                'files.view',
                'timesheets.create',
                'timesheets.view_own',
                'push.receive',
            ],
        ],
        'disposition' => [
            'label' => 'Disposition',
            'permissions' => [
                'dashboard.view',
                'attendance.view',
                'projects.manage',
                'assets.manage',
                'timesheets.view',
                'timesheets.export',
                'reports.export',
                'personnel.view',
                'push.receive',
            ],
        ],
    ],
    'available' => [
        'dashboard.view',
        'attendance.view',
        'users.manage',
        'roles.manage',
        'projects.view',
        'projects.manage',
        'files.view',
        'files.upload',
        'files.manage',
        'assets.manage',
        'assets.assign',
        'timesheets.create',
        'timesheets.view',
        'timesheets.manage',
        'timesheets.archive',
        'timesheets.export',
        'timesheets.view_own',
        'reports.export',
        'reports.accounting.export',
        'accounting.finalize',
        'time_accounts.view',
        'time_accounts.manage',
        'vacation_requests.view',
        'vacation_requests.manage',
        'personnel.view',
        'personnel.manage',
        'settings.manage',
        'settings.database.manage',
        'terminals.manage',
        'push.receive',
        'push.manage',
    ],
];
